/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import Entities.File;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author Admin
 */
public class ImportDataFromExecel extends javax.swing.JFrame {

    /**
     * Creates new form ImportDataFromExecel
     */
    JTable table;
    DefaultTableModel ImportDataFromExecel;
    
    public ImportDataFromExecel() {
    
    }
    public ImportDataFromExecel(JTable table) {
        initComponents();
        this.table = table;
        setImportTable();
    }

    public void setTable(JTable table) {
        this.table = table;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblImport = new javax.swing.JTable();
        btnImport = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnInsertIntoDB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblImport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Image", "Id", "Name", "unit", "Quantity", "Status", "Note", "nullasdasd"
            }
        ));
        jScrollPane1.setViewportView(tblImport);

        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnInsertIntoDB.setText("Insert Into DB");
        btnInsertIntoDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertIntoDBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInsertIntoDB, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertIntoDB))
                .addGap(0, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setImportTable(){
        Vector col = new Vector();
        for (int i = 0; i < table.getColumnCount(); i++) {
            col.add(table.getColumnName(i));
        }
        DefaultTableModel model = new DefaultTableModel(new Vector(), col);
        tblImport.setModel(model);
    }
    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        ImportDataFromExecel=(DefaultTableModel) tblImport.getModel();
        String currentDirectoryPath ="";
        ImportDataFromExecel.setRowCount(0);
        //File excelFile=null;
        FileInputStream excelFIS = null;
        BufferedInputStream excelBIS = null;
        XSSFWorkbook excelImportToJTable = null;
        // TODO add your handling code here:
        JFileChooser excelFileChooserImport = new JFileChooser(currentDirectoryPath);
        
        excelFileChooserImport.setDialogTitle("Select Excel File");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xlsm");
        excelFileChooserImport.setFileFilter(fnef);
         int excelChooser = excelFileChooserImport.showOpenDialog(null);
         if (excelChooser ==JFileChooser.APPROVE_OPTION) {
            try {
                java.io.File excelFile = excelFileChooserImport.getSelectedFile();
                excelFIS = new FileInputStream(excelFile);
                excelBIS = new BufferedInputStream(excelFIS);
                 excelImportToJTable = new XSSFWorkbook(excelBIS);
                 XSSFSheet excelSheet = excelImportToJTable.getSheetAt(0);
                 for (int i = 0; i <excelSheet.getLastRowNum(); i++) {
                    XSSFRow excelRow = excelSheet.getRow(i);
                     XSSFCell excelImage = excelRow.getCell(0);
                    XSSFCell excelId = excelRow.getCell(1);
                    XSSFCell excelName = excelRow.getCell(2);
                    XSSFCell excelunit = excelRow.getCell(3);
                    XSSFCell excelQuantity = excelRow.getCell(4);
                    XSSFCell excelStatus = excelRow.getCell(5);
                    XSSFCell excelNote = excelRow.getCell(6);
                     System.out.println(excelImage);
                     ImportDataFromExecel.addRow(new Object[]{excelImage, excelId, excelName, excelunit, excelQuantity,excelStatus,excelNote});
                }
                 JOptionPane.showMessageDialog(null, "Imported Successfully !!.....");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ImportDataFromExecel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ImportDataFromExecel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnImportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int rowCount = ImportDataFromExecel.getRowCount();
        for (int i = rowCount -1 ; i >=0; i--) {
            ImportDataFromExecel.removeRow(i);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnInsertIntoDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertIntoDBActionPerformed
        // TODO add your handling code here:
        int jTableRows = tblImport.getRowCount();
        String sql = "";
        for (int i = 0; i <jTableRows ; i++) {
            String Img =ImportDataFromExecel.getValueAt(i, 0).toString();
            String Id =ImportDataFromExecel.getValueAt(i, 1).toString();
            String name =ImportDataFromExecel.getValueAt(i, 2).toString();
            String unit =ImportDataFromExecel.getValueAt(i, 3).toString();
            String Quantity =ImportDataFromExecel.getValueAt(i, 4).toString();
            String status =ImportDataFromExecel.getValueAt(i, 5).toString();
            String note =ImportDataFromExecel.getValueAt(i, 6).toString();
            System.out.println(Img);
            System.out.println(Id);
            System.out.println(name);
            System.out.println(unit);
            System.out.println(Quantity);
            System.out.println(status);
            System.out.println(note);
        }
        //System.out.println(jTableRows);
    }//GEN-LAST:event_btnInsertIntoDBActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnInsertIntoDB;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblImport;
    // End of variables declaration//GEN-END:variables
}
